# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='put yo article right up in here'),
        ),
    ]
