# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='first_name',
            field=models.CharField(default='first name', max_length=50),
        ),
        migrations.AddField(
            model_name='contributor',
            name='last_name',
            field=models.CharField(default='last name', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.CharField(default='path', max_length=500),
        ),
    ]
